apiVersion: v1
kind: ConfigMap
metadata:
  name: campusconnect-common-config
  labels:
    app.kubernetes.io/name: campusconnect
data:
  POSTGRES_HOST: {{ .Values.infrastructure.postgres.name | quote }}
  POSTGRES_PORT: {{ .Values.infrastructure.postgres.port | quote }}
  RABBITMQ_HOST: {{ .Values.infrastructure.rabbitmq.name | quote }}
  RABBITMQ_PORT: {{ .Values.infrastructure.rabbitmq.port | quote }}
  EVENTS_EXCHANGE: "campusconnect.events"
  DLX_EXCHANGE: "campusconnect.dlx"
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRE_MINUTES: "120"
  ACADEMICO_URL: "http://academico:8001"
  PAGOS_URL: "http://pagos:8002"
  NOTIFICACIONES_URL: "http://notificaciones:8003"
  ASISTENCIA_URL: "http://asistencia:8004"
  ANALITICA_URL: "http://analitica:8005"
