apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infrastructure.rabbitmq.name }}
  labels:
    app: {{ .Values.infrastructure.rabbitmq.name }}
spec:
  ports:
    - port: {{ .Values.infrastructure.rabbitmq.port }}
      targetPort: {{ .Values.infrastructure.rabbitmq.port }}
      protocol: TCP
      name: amqp
    - port: {{ .Values.infrastructure.rabbitmq.managementPort }}
      targetPort: {{ .Values.infrastructure.rabbitmq.managementPort }}
      protocol: TCP
      name: management
  selector:
    app: {{ .Values.infrastructure.rabbitmq.name }}
