apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.infrastructure.rabbitmq.name }}
  labels:
    app: {{ .Values.infrastructure.rabbitmq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.infrastructure.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.infrastructure.rabbitmq.name }}
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.infrastructure.rabbitmq.port }}
              name: amqp
            - containerPort: {{ .Values.infrastructure.rabbitmq.managementPort }}
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.infrastructure.rabbitmq.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.infrastructure.rabbitmq.password | quote }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
