apiVersion: v1
kind: Secret
metadata:
  name: campusconnect-secrets
  labels:
    app.kubernetes.io/name: campusconnect
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.infrastructure.postgres.password | quote }}
  POSTGRES_USER: {{ .Values.infrastructure.postgres.user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.infrastructure.rabbitmq.password | quote }}
  RABBITMQ_USER: {{ .Values.infrastructure.rabbitmq.user | quote }}
  JWT_SECRET: {{ .Values.services.gateway.env.JWT_SECRET | quote }}
